### ISSUE TITLE
Problema al solicitar reporte

### ISSUE THREAD

**Issue by seba-rsk** [efdiloreto/ZondaPro#4]
Buenos días Eduardo, como estas?
Ante todo gracias por compartir el codigo de su software. Es de gran utilidad para muchas de nosotros!

Ahora bien, quisiera hacerle una consulta al respecto. Logré generar el instalador a través de pyinstaller, instalando los  "requeriments.txt" sin errores. El programa inicia con normalidad y efectua los cálculos correctamente, pero al solicitar el reporte se cierra sin previo aviso, sin emitir ninguna advertencia.

Sabría indicarme a que puede deberse ese problema? Alguna pista de por donde buscar?

Muchas gracias de nuevo y saludos desde Entre Ríos. Un abrazo.

**Comment by efdiloreto** [comment]
Hola, me alegro que sea util. 

Respecto al problema. Tenes instalado [Pandoc](https://pandoc.org/installing.html)?

**Comment by seba-rsk** [comment]
Entiendo que si. Durante la instalación de los módulos y paquetes no obtuve ningun error.
Te mando una imagen de todos los requerimientos instalados en el entorno virtual.

![image](https://github.com/efdiloreto/ZondaPro/assets/122846041/ae9c64aa-c283-44e7-ad75-fe4b6487f66e)

**Comment by efdiloreto** [comment]
Si, pero necesitas instalar Pandoc por aparte así PyPandoc lo puede detectar.

**Comment by seba-rsk** [comment]
Ahora si.. Instalé Pandoc y Miktex y funciona todo de maravilla.. Un abrazo y mil gracias por la predisposición y amabilidad..

**Comment by efdiloreto** [comment]
De nada! Si podes y sin compromiso después subi el instalador así otros usuarios pueden usarlo. No he podido ponerme a crearlo y estoy recibiendo muchos mails que piden por el.

**Comment by seba-rsk** [comment]
Dale perfecto... Déjame qué estudio un poco más xq soy medio nuevo en esto.. No quiero generar problemas con tu repo..
