### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Vidt1660** [efdiloreto/ZondaPro#5]
Hola sebastian como te habia comentado en la Pc con windows 7 me tira este msj:

![ScreenShot001](https://github.com/efdiloreto/ZondaPro/assets/145592388/41afcb5b-91fc-405d-9513-49534a969449)

**Comment by efdiloreto** [comment]
Windows 7 es dificil que ande, incluso no estoy seguro si Python 3.8 soporta Windows 7.

**Comment by Vidt1660** [comment]
Gracias Eduardo, trato de ver si anda en otra compu de la Pc con Windows 10 / 11 y te comento. Gracias y buen finde!

**Comment by Vidt1660** [comment]
Hola eduardo, como estas? pude correrlo en otra pc con windows10, el unico problema es que cuando clickeo en reporte se cuelga la pc, podras saber a que se debe? O lo estoy instalando quizas mal? Tendras el paso a paso? Gracias y disculpa las molestias

**Comment by efdiloreto** [comment]
Esto debería solucionarlo:
 https://github.com/efdiloreto/ZondaPro/issues/4

**Comment by Vidt1660** [comment]
Hola Eduardo! Te escribo que anduvo perfecto ahora!! Muchisimas Gracias! Sos crack sabelo
